### ISSUE TITLE
Add support for negative timestamps

### ISSUE THREAD

**Issue by stevenpetryk** [streamr-app/streamr-api#99]
For https://github.com/streamr-app/streamr-web/issues/84, I send timestamps at `-1`, indicating that they were drawn before recording began. Thumbnail generation needs to reflect this.

**Comment by stevenpetryk** [comment]
Also, as a further optimization down the road, we can treat `clear`s and `undo`s as destructive when they happen at `time == -1`, and allow them to actually remove lines from the stream data (since the user doesn't have to actually see them getting undone or see the screen getting cleared). This would be a tiny optimization though.

**Comment by GregKWhite** [comment]
Closed via #100
